mod-name: SpaceDust
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - SpaceDust
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.4
    location: s3
deploy:
  SpaceDock:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 537  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 231670  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
